name: branch

on:
  workflow_call:

jobs:
  code-ql:
    uses: onecx-apps/ci-angular/.github/workflows/angular-codeql.yml@v3
    secrets: inherit
  angular:
    uses: onecx-apps/ci-angular/.github/workflows/angular-build.yml@v3
    secrets: inherit
  docker:
    uses: onecx-apps/ci-common/.github/workflows/docker-build.yml@v3
    needs: angular
    secrets: inherit
    with:
      tags: '{{ .Branch }}'
      samoDockerFile: Dockerfile
  helm:
    uses: onecx-apps/ci-common/.github/workflows/helm-build.yml@v3
    needs: docker
    secrets: inherit
    with:
      helmDir: 'helm'